version: '3.9'

services:
  slim:
    build:
      context: .
      dockerfile: dockerfiles/slim.dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
    environment:
      docker: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    depends_on:
      - mysql
  mysql:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: csms_user
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: csms
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS `csms`;CREATE DATABASE IF NOT EXISTS `csms_test`;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "8989:3306"
    restart: unless-stopped
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
volumes:
  mysqldata:
  logs:
    driver: local